# Generated by Django 6.0.5 on 2026-05-09 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('missao', models.TextField()),
                ('visao', models.TextField()),
                ('valores', models.TextField()),
            ],
        ),
    ]
